# Generated by Django 3.0.5 on 2020-08-13 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from core import test_data


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(unique=True)),
            ],
            options={
                'ordering': ['site', 'page_url'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('next', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='core.Visit')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.Page')),
            ],
            options={
                'ordering': ['page', '-started'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner__username', 'name'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.Site'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mm', 'Mouse move'), ('md', 'Mouse down'), ('mu', 'Mouse up'), ('sc', 'Scroll')], max_length=2)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField()),
                ('performed', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.Visit')),
            ],
            options={
                'ordering': ['visit', '-performed'],
            },
        ),
        migrations.RunPython(test_data.create),
    ]
