# Generated by Django 3.0.5 on 2020-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='performed',
            field=models.DateTimeField(),
        ),
    ]
