# Generated by Django 3.0.5 on 2020-08-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200813_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='performed',
            field=models.IntegerField(),
        ),
    ]
