# Generated by Django 3.0.5 on 2020-08-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200813_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['visit', 'performed']},
        ),
    ]
